---
- hosts: dev
  become: True
  tasks:
    - name: Install python pip
      sudo:
        name: python-pip
        state: present
    - name: Install docker
      sudo:
        name: docker
        state: present
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Start the container
      docker_container:
        name: jen-doc
        image:  "vamshima/jen-doc:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
